### ISSUE TITLE
[feat]  ci/cd 구축

### ISSUE THREAD

**Issue by yunhobb** [ALLBACK-2022/DoodleDoodle-v2#27]
## 💡 구현할 기능 설명
- Github Actions을 통한 CI/CD 구축

## ❗체크리스트
- [x] 모든 포지션의 팀원들이 이해할 수 있도록 충분한 설명을 제공하나요?
- [x] 제목 형식을 지키고 브랜치 및 라벨을 할당했나요?

**Comment by ohksj77** [comment]
수고했어~
